#ifndef __H_CR_MSGCODE_H__
#define __H_CR_MSGCODE_H__

typedef enum {
	// riak message code begin -->
	RPB_ERROR_RESP		= 0,
	RPB_PING_REQ		= 1,
	RPB_PING_RESP		= 2,
	RPB_GET_CLIENTID_REQ	= 3,
	RPB_GET_CLIENTID_RESP	= 4,
	RPB_SET_CLIENTID_REQ	= 5,
	RPB_SET_CLIENTID_RESP	= 6,
	RPB_GET_SERVERINFO_REQ	= 7,
	RPB_GET_SERVERINFO_RESP	= 8,
	RPB_GET_REQ		= 9,
	RPB_GET_RESP		= 10,
	RPB_PUT_REQ		= 11,
	RPB_PUT_RESP		= 12,
	RPB_DEL_REQ		= 13,
	RPB_DEL_RESP		= 14,
	RPB_LIST_BUCKETS_REQ	= 15,
	RPB_LIST_BUCKETS_RESP	= 16,
	RPB_LIST_KEYS_REQ	= 17,
	RPB_LIST_KEYS_RESP	= 18,
	RPB_GET_BUCKET_REQ	= 19,
	RPB_GET_BUCKET_RESP	= 20,
	RPB_SET_BUCKET_REQ	= 21,
	RPB_SET_BUCKET_RESP	= 22,
	RPB_MAPRED_REQ		= 23,
	RPB_MAPRED_RESP		= 24,
	RPB_INDEX_REQ		= 25,
	RPB_INDEX_RESP		= 26,
	RPB_SEARCH_QUERY_REQ	= 27,
	RPB_SEARCH_QUERY_RESP	= 28,
	// <-- riak message code end

	// cluster-fm message code begin -->
	CFM_ERROR_RESP		= 64,
	CFM_PING_REQ		= 65,
	CFM_PING_RESP		= 66,
	CFM_JOB_START_REQ	= 67,
	CFM_JOB_START_RESP	= 68,
	CFM_JOB_STOP_REQ	= 69,
	CFM_JOB_STOP_RESP	= 70,
	CFM_JOB_QUERY_REQ	= 71,
	CFM_JOB_QUERY_RESP	= 72,
	CFM_JOB_DATA_REQ	= 73,
	CFM_JOB_DATA_RESP	= 74,
	CFM_JOB_CLEAR_REQ	= 75,
	CFM_JOB_CLEAR_RESP	= 76,
	CFM_JOB_KVPUT_REQ	= 77,
	CFM_JOB_KVPUT_RESP	= 78,
	CFM_JOB_KVGET_REQ	= 79,
	CFM_JOB_KVGET_RESP	= 80,
	CFM_JOB_CANCEL_REQ	= 81,
	CFM_JOB_CANCEL_RESP	= 82,
	CFM_ID_REQ		= 83,
	CFM_ID_RESP		= 84,
	CFM_SETJOBID_REQ	= 85,
	CFM_SETJOBID_RESP	= 86,
	// <-- cluster-fm message code end

	USER_MSG_0		= 100,
	USER_MSG_1		= 101,
	USER_MSG_2		= 102,
	USER_MSG_3		= 103,
	USER_MSG_4		= 104,
	USER_MSG_5		= 105,
	USER_MSG_6		= 106,
	USER_MSG_7		= 107,

	LOCK_REQ		= 124,
	LOCK_RESP		= 125,
	UNLOCK_REQ		= 126,
	UNLOCK_RESP		= 127,

	UNDEFINED_REQ		= -127,
	UNDEFINED_RESP		= -126,
	UNKNOWN_REQ		= -3,
	UNKNOWN_RESP		= -2
} cr_msgcode_t;

#endif /* __H_CR_MSGCODE_H__ */
